### ISSUE TITLE
would you consider supporting concealing fields from a line?

### ISSUE THREAD

**Issue by haolian9** [vigoux/azy.nvim#1]
this feature is something more like [fzf's with-nth](https://github.com/junegunn/fzf/issues/102)

take an example, the following lines are what `vim.lsp.buf.document_symbol()` generated.

since the results all lay in the current buffer, the file path, row, col
fields are actually noises to me, they fill my eyes and take account in the
search. as an user, i really want to erase them from the list.

so would you consider having this feature?

```
runtime/lua/vim/lsp.lua|1 col 7| [Variable] default_handlers
runtime/lua/vim/lsp.lua|2 col 7| [Variable] log
runtime/lua/vim/lsp.lua|3 col 7| [Variable] lsp_rpc
runtime/lua/vim/lsp.lua|4 col 7| [Variable] protocol
runtime/lua/vim/lsp.lua|5 col 7| [Variable] util
runtime/lua/vim/lsp.lua|6 col 7| [Variable] sync
runtime/lua/vim/lsp.lua|8 col 7| [Variable] vim
runtime/lua/vim/lsp.lua|9 col 7| [Variable] api
runtime/lua/vim/lsp.lua|10 col 7| [Variable] nvim_err_writeln
runtime/lua/vim/lsp.lua|10 col 25| [Variable] nvim_buf_get_lines
runtime/lua/vim/lsp.lua|10 col 45| [Variable] nvim_command
runtime/lua/vim/lsp.lua|10 col 59| [Variable] nvim_buf_get_option
runtime/lua/vim/lsp.lua|10 col 80| [Variable] nvim_exec_autocmds
runtime/lua/vim/lsp.lua|16 col 7| [Variable] uv
runtime/lua/vim/lsp.lua|17 col 7| [Variable] tbl_isempty
runtime/lua/vim/lsp.lua|17 col 20| [Variable] tbl_extend
runtime/lua/vim/lsp.lua|18 col 7| [Variable] validate
runtime/lua/vim/lsp.lua|19 col 7| [Variable] if_nil
runtime/lua/vim/lsp.lua|21 col 7| [Object] lsp
runtime/lua/vim/lsp.lua|22 col 3| [Variable] protocol
runtime/lua/vim/lsp.lua|24 col 3| [Variable] handlers
runtime/lua/vim/lsp.lua|26 col 3| [Variable] buf
runtime/lua/vim/lsp.lua|27 col 3| [Variable] diagnostic
runtime/lua/vim/lsp.lua|28 col 3| [Variable] codelens
runtime/lua/vim/lsp.lua|29 col 3| [Variable] util
runtime/lua/vim/lsp.lua|32 col 3| [Variable] rpc
runtime/lua/vim/lsp.lua|35 col 3| [Variable] rpc_response_error
runtime/lua/vim/lsp.lua|39 col 5| [Object] lsp._request_name_to_capability
```

**Comment by haolian9** [comment]
i dont known if it's too early to open such an issue, if so, sorry about that.

**Comment by vigoux** [comment]
It is not to early.
Quite frankly I think that the easiest would be to add a builtin for `document_symbols` rather than this.

My idea about this plugin is to add dedicated builtins/sources/sinks so that the UI is always nicely presented.

I'll push a new builtin with this lsp method ASAP.

**Comment by vigoux** [comment]
So I added a builtin for the document symbols.

Corrently, there is a source that converts the elements of the quickfix list (`:h setqflist-what`) into a ui, and the `sinks.qf_item` can take these and open them correctly.

**Comment by haolian9** [comment]
wow, never thought it can be simple like this.

**Comment by vigoux** [comment]
The design of the plugin _should_ allow to add these kind of features quite easily.

By the way, if you want to discuss a little bit about enhancements, feel free to join the matrix channel !
