### ISSUE TITLE
attempt to call field 'create' (a nil value)

### ISSUE THREAD

**Issue by vsedov** [vigoux/azy.nvim#5]
```
E5108: Error executing lua: ...hare/nvim/site/pack/packer/start/azy.nvim/lua/azy/ui.lua:118: a
ttempt to call field 'create' (a nil value)                                                   
stack traceback:                                                                              
        ...hare/nvim/site/pack/packer/start/azy.nvim/lua/azy/ui.lua:118: in function 'create' 
        ...vim/site/pack/packer/start/azy.nvim/lua/azy/builtins.lua:45: in function <...vim/si
te/pack/packer/start/azy.nvim/lua/azy/builtins.lua:44>
```
This is on latest neovim,Would you like a min config ?

**Comment by haolian9** [comment]
have you ran this command, `make lib`, manually or by a plugin manager hook?

**Comment by vigoux** [comment]
It is indeed pretty weird.
Did you get any error when starting up ? Something about `fzy` not being found ?

If not, there may be _another_ plugin named `fzy` that leads to a name collision

**Comment by vigoux** [comment]
For the record, if you have `nvim-fzy` installed, this may lead to issues as both plugins collide.

This is not notified in the docs since 76dc36cba3f0a15ceeef2a04ff33b7fdd361cf47

**Comment by ghost** [comment]
I get the same error on a different context, I'm on neovim 0.7.2, can I provide more details to help you out? I don't have nvim-fzy installed.

![Screen Shot 2022-09-20 at 16 17 45](https://user-images.githubusercontent.com/78858604/191282438-3b30e9d0-34a8-47fd-986f-6db2897bd644.png)

**Comment by vigoux** [comment]
That's not the same error.
You are using an older version of neovim, this plugin is meant to work with neovim 0.8 (pre-release for now).

**Comment by ghost** [comment]
Ah I see, sorry for bothering you in that case. Looking forward to using the plugin when 0.8 releases 👍🏻

**Comment by vigoux** [comment]
Should be in the following month or so, so I'll gladly take your feedback then !

**Comment by vsedov** [comment]
> Did you get any error when starting up ? Something about `fzy` not being found ?

Yeah pretty much 


> For the record, if you have `nvim-fzy` installed, this may lead to issues as both plugins collide.
> 
> This is not notified in the docs since [76dc36c](https://github.com/vigoux/azy.nvim/commit/76dc36cba3f0a15ceeef2a04ff33b7fdd361cf47)

Ah that could be it, I have fzf-lua installed atm.  But even without it, I seem to get the same error ? I don't seem to have any fzy related plugins installed though 

Recent update  513cf70576b37b0f1f776003e33ffaa7837acce2 ```make lib``` stoped working btw.

**Comment by vsedov** [comment]
Il keep playing around and see if there is a plugin causing this issue.

**Comment by vsedov** [comment]
Alright so I figured out the problem:  [guihua](https://github.com/ray-x/guihua.lua/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) Seems to be causing it.  Seems to be working, but I'm on b3e6577318ec496f22204ee9eed32656c6c3156a atm, master doesn't want to ```make lib``` >.<

**Comment by vigoux** [comment]
Yeah I discovered `guihua` just now, and it may lead to issues because of `fzy-lua-native`.

Regarding master being broken, I am going to setup CI at the same time, to avoid breaking things more in the future :wink:

**Comment by vigoux** [comment]
`master` should be fixed now.
Sorry for the unstability, I am going to setup CI today, and the testing infrastructure, so that should be gone soon.

**Comment by vigoux** [comment]
For the record: master is now fixed, and everything is ensured on CI !

~~Furthermore @unansweredocd the CI will enforce the use of the latest released version of neovim (that is 0.7 for now), so you'll be able to use the plugin as soon as that's fixed.~~

EDIT: Nevermind this plugin uses neovim 0.8 functionnalities too much, we'll have to wait for it to release.

**Comment by ghost** [comment]
No worries, thank you for putting in so much work on this and neovim itself, it makes my day job way easier.

**Comment by vigoux** [comment]
And thanks for using all this, I really appreciate it !
