### ISSUE TITLE
Highlight groups not working

### ISSUE THREAD

**Issue by Gaulm** [vigoux/azy.nvim#6]
The highlight groups mentioned in the readme do not work.

**Comment by vigoux** [comment]
Can you be a little more precise about that ?
They are all defined correctly and used in the code, so I wonder what you mean.

**Comment by Gaulm** [comment]
I'm trying to customize Azy groups for my colorscheme, but they do not seem to affect the colors in any way.
I'm referring to `AzyMatch`, `AzyDim` and `AzyStandout`.

To reproduce, I have this line right after the azy setup:
```lua
vim.api.nvim_set_hl(0, "AzyMatch", { foreground = "#151515", background = "#151515" })
```
The background of the matching entries remains red, unaffected.

**Comment by vigoux** [comment]
That was a mistake from me, could you update the plugin and confirm that the issue is gone ?

Thanks for reporting this and for the help !
