### ISSUE TITLE
Change keymap for up and down navigation

### ISSUE THREAD

**Issue by ghost** [vigoux/azy.nvim#7]
Hey,

Thanks for creating this. Been trying it out since the official 0.8 release of neovim.

One thing that I'm trying to figure out is how to navigate up or down, normally I rely on Ctrl-n and Ctrl-p to go down and up but that doesn't work. What happens instead is that I see the following.

When I toggle find files (correct)

![Screen Shot 2022-10-04 at 17 11 52](https://user-images.githubusercontent.com/78858604/193857308-b203df7b-da60-466b-b3cd-e212747a60b7.png)

When I press Ctrl-N after (incorrect, I think?)

![Screen Shot 2022-10-04 at 17 12 34](https://user-images.githubusercontent.com/78858604/193857514-285e47f8-e8af-43d7-87ab-b63aa1f4ac17.png)

Is there any way to remap the up and down actions to Ctrl-n and Ctrl-p? That would solve my issue.

**Comment by vigoux** [comment]
Hi and thanks for using this plugin !

I am going to add a way to customize mappings !
I don't think that mapping `<C-n>` and `<C-p>` will become the default though.

**Comment by ghost** [comment]
That's awesome, no rush.

**Comment by vigoux** [comment]
Hi, could you confirm that this has been fixed in latest master ?

You should be able to check that by doing:
```lua
require'azy'.setup {
  mappings = {
    ['<C-n>'] = 'next',
    ['<C-p>'] = 'prev'
  }
}
```

**Comment by ghost** [comment]
Thank you so much for doing this, it works perfectly 👍🏻

**Comment by vigoux** [comment]
Awesome ! Thanks for your contribution, and feel free to report anything else that bothers you !
